# services:
#   - name: ollama-service
#     type: web
#     repo: https://github.com/almustarik/ollama-backend
#     branch: main
#     env: docker
#     plan: free
#     autoDeploy: true
#     envVars:
#       - key: PORT
#         value: '11434'
#     disk:
#       name: ollama-cache
#       mountPath: /root/.ollama
#       sizeGB: 5
# startCommand: |
#       ollama serve & sleep 3 &&
#       ollama pull llama3 && tail -f /dev/null

services:
  - name: ollama-service
    type: web
    runtime: docker
    repo: https://github.com/almustarik/ollama-backend # Change this to your repo
    region: oregon # Change if needed
    plan: free # Use "starter" for better performance
    envVars:
      - key: "OLLAMA_MODEL"
        value: "llama3"
    envVars:
      - key: PORT
        value: '11434'
    dockerfilePath: ./Dockerfile
    disk:
      name: ollama-data
      mountPath: /root/.ollama
      sizeGB: 5
    startCommand: |
      ollama serve & sleep 3 &&
      ollama pull llama3 &&
      echo "Installed models:" &&
      ollama list &&
      tail -f /dev/null
    healthCheckPath: /
    autoDeploy: true